SuperCuber/dotter

Cargo.lock
Cargo.toml
src/filesystem.rs

Closes #62 
Fixes a bug on macOS where running `dotter deploy` twice would error. The error specifically occurred when attempting to obtain the effective UID of the process.
Use [`libc::geteuid()`](https://docs.rs/libc/0.2.12/libc/fn.geteuid.html) to get the effective UID instead of looking at the metadata for `/proc/self` which does not exist on macOS.

Remove use of /proc/self for macOS compatibility

---

Cargo.lock
Cargo.toml
src/config.rs

Not fully tested nor optimized, but it seems to work.
Let me know if you want me to restructure anything (like the location of the `file_exists()` function)
Ideally we would only check the hostname if `local.toml` isn't found, but I ran into lifetime errors since the hostname variable would expire before loading the config, unless I duplicated the code for loading the file (one if local.toml was found, and another if it wasn't).

Use <hostname>.toml if local.toml is not found

---

README.md

Dotter has been added to Scoop's Main bucket

Add scoop install instruction

---

src/filesystem.rs

If a directory `source_dir` exists and contains a file `foo`, and Dotter's config contains `source_dir = "target_dir"`, Dotter will create `target_dir` and link `target_dir/foo` to `source_dir/foo`. If `source_dir/foo` is then deleted, `dotter deploy` will fail:
```
[ERROR] Failed to delete symlink "source_dir/foo" -> "target_dir/foo"
Caused by:
detect symlink's current state
get real path of source
No such file or directory (os error 2)
```
I believe this is the same problem reported by @lumbo7332 in https://github.com/SuperCuber/dotter/issues/55#issuecomment-879532271, and this PR should fix it. It does not address #55 itself, as that seems to be caused by Dotter not handling nonexistent source files gracefully, rather than anything to do with broken symlinks.
As one of my commit …

Fix file-not-found errors when handling broken symlinks

---

src/hooks.rs

Until now dotter forced script execution through sh and so totally ignoring shebang if exists.
That prevent using other script language than sh like bash, python or whatever
To keep a kind of backward compat, this addition will only run script directly if script file is executable otherwise we fallback on previous way to execute.
Fixes #73
---
Still in draft due to https://github.com/SuperCuber/dotter/issues/73#issuecomment-1004407144

Check if hooks are executable to be self executed

---

src/config.rs
src/deploy.rs
src/filesystem.rs
src/handlebars_helpers.rs

This adds an option for dealing with both directory sources and symlinks. When `recurse` is set to false, a source is not traversed until it lands on a regular file; it stops there and makes the source directory/symlink the target of the destination symlink. This option can be set per `SymbolicTarget` to retain the default behavior for other packages, or it can be set at the global level to change the default behavior, i.e. it makes the sources and destinations "what you see is what you get", for those who might prefer this behavior. It retains the default behavior to avoid breakage.
Fixes #92
I know you expressed a desire in #89 for tests; however, this is proving to be time consuming, as it does not look like the existing recursive behavior has any existing regression tests, and what …

add options for disabling recursion

---

Cargo.lock

Some macro in rhai failed building with rust 1.61. `cargo update` fixes it.

fix build failing with rust 1.61

---

Cargo.lock
Cargo.toml
README.md
src/args.rs

Most of the features of structopt are now in clap v3.

Using clap instead of structopt

---

Cargo.lock
Cargo.toml
README.md
src/args.rs
src/main.rs

There is an issue for that (https://github.com/SuperCuber/dotter/issues/65), it prints to stdout the completion.
It is intended to be use like: 
`dotter gen-completions --shell "zsh" >> ./file.txt`

Adding generation of shell completions

---

src/args.rs
src/deploy.rs
src/filesystem.rs

I introduced a bug in #108, the flags `dry-run` and `interactive` were true by default.

Fix inverted flags

---

src/config.rs
src/handlebars_helpers.rs

Include disabled packages in dotter.packages

---

src/actions.rs
src/hooks.rs

Running dotter with a second user panicked, because it didn't have permission to delete the temp-file that was created by the first user. And I also didn't expect that the hook-scripts get stored world readable outside of the users home. It's not a problem for me, but it might contain secrets from the `local.toml`, which users don't expect to leak somewhere else.
There is no need to copy the hook scripts to somewhere else, it can be run directly from the cache, so that's what I implemented.
Other possible solutions I considered were creating a temp-file with a random name (or containing the username) and delete it again after the hook was run. But that would still leave the problem of maybe causing to leak the rendered hook script unintentionally. As even if the temp-file gets initially …

Run hook scripts directly from cache directory

---

src/handlebars_helpers.rs

Sometimes, for example when referencing a file in a config, a relative path is enough, so no issues in this case. And some configs are scripts (for example zsh configs), so I can access the env-vars also easily  at runtime. But some configs require absolute paths, and also aren't scripts. So if I need to reference a file in the /home directory of the user, I need the path at render-time. My current workaround is `{{ command_output "echo -n ${HOME}" }}`, that works, but isn't nice. So just being able to access the env-vars directly at render-time with `{{ env "HOME" }}` makes this a lot easier. :)
So this is mostly for me to have access to `$HOME` and `$USER` env vars, but since it's maybe also useful for other env-vars in the future, I directly created a dynamic helper to give access to …

Add handlebars helper to print environment variables

---

src/handlebars_helpers.rs

As mentioned in https://github.com/SuperCuber/dotter/pull/138#issuecomment-1668821605, this was already possible with the `env_var` helper from [handlebars_misc_helpers](https://github.com/davidB/handlebars_misc_helpers/#environment-variable), I just somehow overlooked the link to that when I searched if something like that is already possible in the wiki (I swear I looked at the wiki so many times, but I somehow missed it every single time, I must be blind). Sorry about the chaos.

Revert "Add handlebars helper to print environment variables (#138)"

---

src/handlebars_helpers.rs

This change allows using the `assign` helper from `handlebars_misc_helpers` to pass variables into templates rendered with `include_template`. The `assign` helper modifies the `RenderContext` and previously `include_template` would use the `Context` when rendering the template. The change attempts to use the `RenderContext` with a fallback to use the `Context` if no `RenderContext` exists.
Note that this change does not address `handlebars_misc_helpers` #65. The `assign` helper clones the `Context` and overwrites the `RenderContext` on every call meaning that only variables defined by the most recent `assign` call will be available.
Resolves #134.
@SuperCuber, thanks for your time so far. I've put this PR together assuming no changes are made in `handlebars_misc_helpers`. I didn't add any …

Allow passing variables defined by `assign` to `include_template`.

---

Cargo.toml

This PR aims to reduce the size of the compiled `dotter` binary. I'm taking your advice and including the final binary in my dotfiles but I thought the final binary size was a bit larger than I'd like. I followed the steps [here](https://github.com/johnthagen/min-sized-rust) and reduced the file size from 17M to 4.9M.
This PR adds 5 new flags to the release profile in Cargo.toml:
- `strip = true`: strip symbols
- `opt-level = "z"`: optimize for file size instead of execution speed (more below)
- `lto = true`: enable Link Time Optimization
- `codegen-units = 1`: reduces parallel codegen units from 16 to 1
- `panic = "abort"`: prevents unwinding the stack on a panic and prevents displaying a stacktrace
The `strip` and `lto` optimizations have no downsizes but the others have some potential …

Optmize binary size

---

Cargo.toml

This improves the error message when using an older compiler. I got a "use of unstable feature is_ok_and" error because I was still on 1.68.

Indicate required Rust version

---

Cargo.lock
Cargo.toml
src/handlebars_helpers.rs

The new version now supports a syntax like this:
```handlebars
{{#if ...}}
{{else if ...}}
{{else}}
{{/if}}
```
Also update `handlebars_misc_helpers` to be compatible with the new `handlebars` version.
Also refactor `RenderError`s to `RenderErrorReason`s to fix deprecation warnings.

Upgrade handlebars to version 5.1 to support chained else expression

---

src/config.rs

I have some configs for work, which I didn't want to add to my main repo, and I created a separate repo for it, which I then included in the `local.toml` only on my work PC. This works fine as long as I only want to add additional files to existing packages. But when I wanted to add a config for a package which isn't in my main `global.toml`, it failed. I needed to create an empty package in the `global.toml` to which I then can add the files from my included repo.
With this change, I can include packages from my `local.toml` where the main `global.toml` doesn't need to know anything about it.
I don't know if I'm overlooking something here, and if there was a reason why unknown packages were rejected before (and even made it hard fail and not just print a warning). But in my local testing …

Append new/unknown packages from included files

---

src/config.rs
src/handlebars_helpers.rs

howdy, I am interested in this feature as well, https://github.com/SuperCuber/dotter/issues/169, and took a shot at implementing it. I am not very practiced in rust lately so I just wanted to make sure I could at least get something that worked before getting caught up in any specifics like where to store the config or what to name it.
This PR adds a variables field to the GlobalConfig. Then, when merging and processing the config files, it checks for a field, `enable_symlink_by_default`, and if that is true, it converts any packages with any files that are FileTarget::Automatic to FileTarget::Symbolic. I thought the deployer shouldn't really care about the FileTarget type and decided to handle this conversion in the config. I also added a test to show it converts FileTarget::Automatic …

adding global variable to enable symlinks by default if type not specified

---

Cargo.lock
src/config.rs

seeing some time related failure 
```
error[E0282]: type annotations needed for `Box<_>`
--> /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
|
83 |     let items = format_items
|         ^^^^^
...
86 |     Ok(items.into())
|              ---- type must be known at this point
|
help: consider giving `items` an explicit type, where the placeholders `_` are specified
|
83 |     let items: Box<_> = format_items
|              ++++++++
```
has been addressed with 0.3.36, https://github.com/time-rs/time/issues/693

chore: update to build with rust 1.80
